// @flow

const REQUEST_SIGNIN: string = 'REQUEST_SIGNIN';
const REQUEST_SIGNOUT: string = 'REQUEST_SIGNOUT';
const REQUEST_BANNER: string = 'REQUEST_BANNER';
const REQUEST_BANNER_SUCCESS: string = 'REQUEST_BANNER_SUCCESS';
const REQUEST_BANNER_FAIL: string = 'REQUEST_BANNER_FAIL';

export {
  REQUEST_SIGNIN,
  REQUEST_SIGNOUT,
  REQUEST_BANNER,
  REQUEST_BANNER_SUCCESS,
  REQUEST_BANNER_FAIL
};
